#############################################################################
# Makefile for building: updatedblocal
# Generated by qmake (3.1) (Qt 5.8.0)
# Project:  ../updatedblocal12122019/updatedblocal.pro
# Template: app
# Command: /opt/fslc-framebuffer/2.3/icore/sysroots/x86_64-fslcsdk-linux/usr/bin/qt5/qmake -o Makefile ../updatedblocal12122019/updatedblocal.pro -spec linux-oe-g++
#############################################################################

MAKEFILE      = Makefile

####### Compiler, tools and options

CC            = arm-fslc-linux-gnueabi-gcc  -march=armv7-a -mthumb -mfpu=neon  -mfloat-abi=hard --sysroot=/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi
CXX           = arm-fslc-linux-gnueabi-g++  -march=armv7-a -mthumb -mfpu=neon  -mfloat-abi=hard --sysroot=/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi
DEFINES       = -DQT_NO_DEBUG -DQT_WIDGETS_LIB -DQT_GUI_LIB -DQT_SQL_LIB -DQT_CORE_LIB
CFLAGS        = -pipe  -O2 -pipe --sysroot=/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
CXXFLAGS      = -pipe --sysroot=/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi -O2 -Wall -W -D_REENTRANT -fPIC $(DEFINES)
INCPATH       = -I../updatedblocal12122019 -I. -isystem /opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/include/qt5 -isystem /opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/include/qt5/QtWidgets -isystem /opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/include/qt5/QtGui -isystem /opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/include/qt5/QtSql -isystem /opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/include/qt5/QtCore -I. -I/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/linux-oe-g++
QMAKE         = /opt/fslc-framebuffer/2.3/icore/sysroots/x86_64-fslcsdk-linux/usr/bin/qt5/qmake
DEL_FILE      = rm -f
CHK_DIR_EXISTS= test -d
MKDIR         = mkdir -p
COPY          = cp -f
COPY_FILE     = cp -f
COPY_DIR      = cp -f -R
INSTALL_FILE  = install -m 644 -p
INSTALL_PROGRAM = install -m 755 -p
INSTALL_DIR   = cp -f -R
DEL_FILE      = rm -f
SYMLINK       = ln -f -s
DEL_DIR       = rmdir
MOVE          = mv -f
TAR           = tar -cf
COMPRESS      = gzip -9f
DISTNAME      = updatedblocal1.0.0
DISTDIR = /home/user/ECOFILL/updatedblocal/.tmp/updatedblocal1.0.0
LINK          = arm-fslc-linux-gnueabi-g++  -march=armv7-a -mthumb -mfpu=neon  -mfloat-abi=hard --sysroot=/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi
LFLAGS        = -Wl,-O1 --sysroot=/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi -Wl,-O1
LIBS          = $(SUBLIBS) -lQt5Widgets -lQt5Gui -lQt5Sql -lQt5Core -lGLESv2 -lEGL -lpthread 
AR            = arm-fslc-linux-gnueabi-ar cqs
RANLIB        = 
SED           = sed
STRIP         = 

####### Output directory

OBJECTS_DIR   = ./

####### Files

SOURCES       = ../updatedblocal12122019/main.cpp \
		../updatedblocal12122019/grddataobject.cpp \
		../updatedblocal12122019/grdsplashmessage.cpp moc_grdsplashmessage.cpp
OBJECTS       = main.o \
		grddataobject.o \
		grdsplashmessage.o \
		moc_grdsplashmessage.o
DIST          = /opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/spec_pre.prf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/common/unix.conf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/common/linux.conf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/common/sanitize.conf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/common/gcc-base.conf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/common/gcc-base-unix.conf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/common/g++-base.conf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/common/g++-unix.conf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/oe-device-extra.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/qdevice.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/device_config.prf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/qconfig.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_core.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_enginio.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_enginio_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_gui.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_network.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_nfc.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_publishsubscribe.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_publishsubscribe_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_qml.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_quick.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_script.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_script_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_serviceframework.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_serviceframework_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_sql.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_svg.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_systeminfo.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_systeminfo_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_xml.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_zlib_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/qt_functions.prf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/qt_config.prf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/linux-oe-g++/qmake.conf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/spec_post.prf \
		../updatedblocal12122019/.qmake.stash \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/exclusive_builds.prf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/toolchain.prf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/default_pre.prf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/resolve_config.prf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/default_post.prf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/warn_on.prf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/qt.prf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/resources.prf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/moc.prf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/unix/opengl.prf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/uic.prf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/unix/thread.prf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/qmake_use.prf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/file_copies.prf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/testcase_targets.prf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/exceptions.prf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/yacc.prf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/lex.prf \
		../updatedblocal12122019/updatedblocal.pro ../updatedblocal12122019/grddataobject.h \
		../updatedblocal12122019/grdsplashmessage.h ../updatedblocal12122019/main.cpp \
		../updatedblocal12122019/grddataobject.cpp \
		../updatedblocal12122019/grdsplashmessage.cpp
QMAKE_TARGET  = updatedblocal
DESTDIR       = 
TARGET        = updatedblocal


first: all
####### Build rules

$(TARGET):  $(OBJECTS)  
	$(LINK) $(LFLAGS) -o $(TARGET) $(OBJECTS) $(OBJCOMP) $(LIBS)

Makefile: ../updatedblocal12122019/updatedblocal.pro /opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/linux-oe-g++/qmake.conf /opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/spec_pre.prf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/common/unix.conf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/common/linux.conf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/common/sanitize.conf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/common/gcc-base.conf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/common/gcc-base-unix.conf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/common/g++-base.conf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/common/g++-unix.conf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/oe-device-extra.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/qdevice.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/device_config.prf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/qconfig.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_bluetooth.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_concurrent.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_concurrent_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_core.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_core_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_dbus.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_dbus_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_egl_support_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_enginio.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_enginio_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_fb_support_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_gui.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_gui_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_input_support_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_multimedia.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_multimedia_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_network.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_network_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_nfc.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_nfc_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_opengl.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_opengl_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_openglextensions.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_printsupport.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_printsupport_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_publishsubscribe.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_publishsubscribe_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_qml.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_qml_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_qmltest.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_qmltest_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_quick.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_quick_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_quickwidgets.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_script.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_script_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_scripttools.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_scripttools_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_serialport.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_serialport_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_service_support_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_serviceframework.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_serviceframework_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_sql.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_sql_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_svg.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_svg_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_systeminfo.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_systeminfo_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_testlib.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_testlib_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_theme_support_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_widgets.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_widgets_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_xml.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_xml_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_zlib_private.pri \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/qt_functions.prf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/qt_config.prf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/linux-oe-g++/qmake.conf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/spec_post.prf \
		.qmake.stash \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/exclusive_builds.prf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/toolchain.prf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/default_pre.prf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/resolve_config.prf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/default_post.prf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/warn_on.prf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/qt.prf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/resources.prf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/moc.prf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/unix/opengl.prf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/uic.prf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/unix/thread.prf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/qmake_use.prf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/file_copies.prf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/testcase_targets.prf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/exceptions.prf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/yacc.prf \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/lex.prf \
		../updatedblocal12122019/updatedblocal.pro \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/libQt5Widgets.prl \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/libQt5Gui.prl \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/libQt5Sql.prl \
		/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/libQt5Core.prl
	$(QMAKE) -o Makefile ../updatedblocal12122019/updatedblocal.pro -spec linux-oe-g++
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/spec_pre.prf:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/common/unix.conf:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/common/linux.conf:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/common/sanitize.conf:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/common/gcc-base.conf:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/common/gcc-base-unix.conf:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/common/g++-base.conf:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/common/g++-unix.conf:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/oe-device-extra.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/qdevice.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/device_config.prf:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/qconfig.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_bluetooth.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_bluetooth_private.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_bootstrap_private.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_concurrent.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_concurrent_private.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_core.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_core_private.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_dbus.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_dbus_private.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_devicediscovery_support_private.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_egl_support_private.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_eglfsdeviceintegration_private.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_enginio.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_enginio_private.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_eventdispatcher_support_private.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_fb_support_private.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_fontdatabase_support_private.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_gui.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_gui_private.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_input_support_private.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_multimedia.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_multimedia_private.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_multimediawidgets_private.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_network.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_network_private.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_nfc.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_nfc_private.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_opengl.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_opengl_private.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_openglextensions.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_openglextensions_private.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_platformcompositor_support_private.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_printsupport.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_printsupport_private.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_publishsubscribe.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_publishsubscribe_private.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_qml.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_qml_private.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_qmldevtools_private.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_qmltest.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_qmltest_private.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_qtmultimediaquicktools_private.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_quick.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_quick_private.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_quickparticles_private.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_quickwidgets.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_quickwidgets_private.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_script.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_script_private.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_scripttools.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_scripttools_private.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_serialport.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_serialport_private.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_service_support_private.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_serviceframework.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_serviceframework_private.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_sql.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_sql_private.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_svg.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_svg_private.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_systeminfo.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_systeminfo_private.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_testlib.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_testlib_private.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_theme_support_private.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_widgets.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_widgets_private.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_xml.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_xml_private.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_xmlpatterns.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_xmlpatterns_private.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/modules/qt_lib_zlib_private.pri:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/qt_functions.prf:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/qt_config.prf:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/linux-oe-g++/qmake.conf:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/spec_post.prf:
.qmake.stash:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/exclusive_builds.prf:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/toolchain.prf:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/default_pre.prf:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/resolve_config.prf:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/default_post.prf:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/warn_on.prf:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/qt.prf:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/resources.prf:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/moc.prf:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/unix/opengl.prf:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/uic.prf:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/unix/thread.prf:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/qmake_use.prf:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/file_copies.prf:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/testcase_targets.prf:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/exceptions.prf:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/yacc.prf:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/lex.prf:
../updatedblocal12122019/updatedblocal.pro:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/libQt5Widgets.prl:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/libQt5Gui.prl:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/libQt5Sql.prl:
/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/libQt5Core.prl:
qmake: FORCE
	@$(QMAKE) -o Makefile ../updatedblocal12122019/updatedblocal.pro -spec linux-oe-g++

qmake_all: FORCE


all: Makefile $(TARGET)

dist: distdir FORCE
	(cd `dirname $(DISTDIR)` && $(TAR) $(DISTNAME).tar $(DISTNAME) && $(COMPRESS) $(DISTNAME).tar) && $(MOVE) `dirname $(DISTDIR)`/$(DISTNAME).tar.gz . && $(DEL_FILE) -r $(DISTDIR)

distdir: FORCE
	@test -d $(DISTDIR) || mkdir -p $(DISTDIR)
	$(COPY_FILE) --parents $(DIST) $(DISTDIR)/
	$(COPY_FILE) --parents /opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/data/dummy.cpp $(DISTDIR)/
	$(COPY_FILE) --parents ../updatedblocal12122019/grddataobject.h ../updatedblocal12122019/grdsplashmessage.h $(DISTDIR)/
	$(COPY_FILE) --parents ../updatedblocal12122019/main.cpp ../updatedblocal12122019/grddataobject.cpp ../updatedblocal12122019/grdsplashmessage.cpp $(DISTDIR)/


clean: compiler_clean 
	-$(DEL_FILE) $(OBJECTS)
	-$(DEL_FILE) *~ core *.core


distclean: clean 
	-$(DEL_FILE) $(TARGET) 
	-$(DEL_FILE) .qmake.stash
	-$(DEL_FILE) Makefile


####### Sub-libraries

mocclean: compiler_moc_header_clean compiler_moc_source_clean

mocables: compiler_moc_header_make_all compiler_moc_source_make_all

check: first

benchmark: first

compiler_rcc_make_all:
compiler_rcc_clean:
compiler_moc_predefs_make_all: moc_predefs.h
compiler_moc_predefs_clean:
	-$(DEL_FILE) moc_predefs.h
moc_predefs.h: /opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/data/dummy.cpp
	arm-fslc-linux-gnueabi-g++  -march=armv7-a -mthumb -mfpu=neon  -mfloat-abi=hard --sysroot=/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi -pipe --sysroot=/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi -O2 -Wall -W -dM -E -o moc_predefs.h /opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/features/data/dummy.cpp

compiler_moc_header_make_all: moc_grdsplashmessage.cpp
compiler_moc_header_clean:
	-$(DEL_FILE) moc_grdsplashmessage.cpp
moc_grdsplashmessage.cpp: ../updatedblocal12122019/grddataobject.h \
		../updatedblocal12122019/grdsplashmessage.h \
		moc_predefs.h \
		/opt/fslc-framebuffer/2.3/icore/sysroots/x86_64-fslcsdk-linux/usr/bin/qt5/moc
	/opt/fslc-framebuffer/2.3/icore/sysroots/x86_64-fslcsdk-linux/usr/bin/qt5/moc $(DEFINES) --include ./moc_predefs.h -I/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/qt5/mkspecs/linux-oe-g++ -I/home/user/ECOFILL/updatedblocal12122019 -I/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/include/qt5 -I/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/include/qt5/QtWidgets -I/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/include/qt5/QtGui -I/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/include/qt5/QtSql -I/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/include/qt5/QtCore -I. -I/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/include/c++/6.3.0 -I/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/include/c++/6.3.0/arm-fslc-linux-gnueabi -I/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/include/c++/6.3.0/backward -I/opt/fslc-framebuffer/2.3/icore/sysroots/x86_64-fslcsdk-linux/usr/lib/arm-fslc-linux-gnueabi/gcc/arm-fslc-linux-gnueabi/6.3.0/include -I/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/lib/gcc/arm-fslc-linux-gnueabi/6.3.0/include -I/opt/fslc-framebuffer/2.3/icore/sysroots/x86_64-fslcsdk-linux/usr/lib/arm-fslc-linux-gnueabi/gcc/arm-fslc-linux-gnueabi/6.3.0/include-fixed -I/opt/fslc-framebuffer/2.3/icore/sysroots/armv7at2hf-neon-fslc-linux-gnueabi/usr/include ../updatedblocal12122019/grdsplashmessage.h -o moc_grdsplashmessage.cpp

compiler_moc_source_make_all:
compiler_moc_source_clean:
compiler_uic_make_all:
compiler_uic_clean:
compiler_yacc_decl_make_all:
compiler_yacc_decl_clean:
compiler_yacc_impl_make_all:
compiler_yacc_impl_clean:
compiler_lex_make_all:
compiler_lex_clean:
compiler_clean: compiler_moc_predefs_clean compiler_moc_header_clean 

####### Compile

main.o: ../updatedblocal12122019/main.cpp ../updatedblocal12122019/grdsplashmessage.h \
		../updatedblocal12122019/grddataobject.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o main.o ../updatedblocal12122019/main.cpp

grddataobject.o: ../updatedblocal12122019/grddataobject.cpp ../updatedblocal12122019/grddataobject.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o grddataobject.o ../updatedblocal12122019/grddataobject.cpp

grdsplashmessage.o: ../updatedblocal12122019/grdsplashmessage.cpp ../updatedblocal12122019/grdsplashmessage.h \
		../updatedblocal12122019/grddataobject.h
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o grdsplashmessage.o ../updatedblocal12122019/grdsplashmessage.cpp

moc_grdsplashmessage.o: moc_grdsplashmessage.cpp 
	$(CXX) -c $(CXXFLAGS) $(INCPATH) -o moc_grdsplashmessage.o moc_grdsplashmessage.cpp

####### Install

install:  FORCE

uninstall:  FORCE

FORCE:

